#!/bin/bash

# 定义起始时间
TEST_TIME_START=20

# 定义时间增量
TEST_TIME_INCREMENT=5

# 定义起始连接数
START_CONNECTIONS=10000

# 定义连接数的增量
CONNECTION_INCREMENT=1000

# 目标URL
URL="http://localhost:80/"

echo "time: $(date +"%T")"

# 循环测试不同的连接数
for (( i = START_CONNECTIONS; i <= 50000; i += CONNECTION_INCREMENT )); do

    for (( t = TEST_TIME_START; t <= 60; t += TEST_TIME_INCREMENT )); do

        ./webbench -2 -t $t -c $i $URL
        echo "time: $(date +"%T")"

    done

done


